spring:
  mail:
    host: smtp.qq.com
    username: 3095764372@qq.com
    password: fatwmcjcvqpqdhcd
    nickname: GG
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
